name: Spider

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
        
    - name: Delete workflows
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0 
        #The number of days that is used to compare with the retention days of each workflow.
        #用于与每个工作流程的保留天数进行比较的天数。
        keep_minimum_runs: 2 
        #The minimum runs to keep for each workflow.
        #每个工作流程要保留的最少运行次数。
        
    - name: Clone project
      run: |

        rm -rf project
        # 删除 jar/custom_spider.jar
        rm -rf jar/custom_spider.jar
        # 克隆 FongMi/CatVodSpider 仓库到 project 目录，并递归克隆子模块。
        git clone --recurse-submodules https://github.com/FongMi/CatVodSpider project

    # 自定义 Spider
    - name: Customize Spider
      working-directory: ./project
      run: |


        #sed -i 's/gradle-7.4.2-all/gradle-7.5-bin/g' gradle/wrapper/gradle-wrapper.properties

        sed -i 's/www.wogg.net/www.wogg.link/g' app/src/main/java/com/github/catvod/spider/Wogg.java
        sed -i 's/www.aliyundrive.com/(www.alipan.com|www.aliyundrive.com)/g' app/src/main/java/com/github/catvod/spider/Zhaozy.java
        sed -i 's/api2.rinhome.com/112.124.0.131:20000/g' app/src/main/java/com/github/catvod/spider/Jianpian.java
        
        # cp ../app/src/main/java/com/github/catvod/spider/Nongm.java app/src/main/java/com/github/catvod/spider/Nongm.java
        # cp ../app/src/main/java/com/github/catvod/spider/FengGo.java app/src/main/java/com/github/catvod/spider/FengGo.java
        cp ../app/src/main/java/com/github/catvod/spider/Ikanbot.java app/src/main/java/com/github/catvod/spider/Ikanbot.java
        cp ../app/src/main/java/com/github/catvod/spider/Auete.java app/src/main/java/com/github/catvod/spider/Auete.java
        # cp ../app/src/main/java/com/github/catvod/spider/ChangZhang.java app/src/main/java/com/github/catvod/spider/ChangZhang.java

        #增加zhixc爬虫
        curl -L https://raw.githubusercontent.com/zhixc/CatVodTVSpider/main/app/src/main/java/com/github/catvod/spider/Anime1.java > app/src/main/java/com/github/catvod/spider/Anime1.java
        #curl -L https://raw.githubusercontent.com/zhixc/CatVodTVSpider/main/app/src/main/java/com/github/catvod/spider/Live2Vod.java > app/src/main/java/com/github/catvod/spider/Live2Vod.java
        #curl -L https://raw.githubusercontent.com/zhixc/CatVodTVSpider/main/app/src/main/java/com/github/catvod/spider/LocalFileV2.java > app/src/main/java/com/github/catvod/spider/LocalFileV2.java
        #curl -L https://raw.githubusercontent.com/zhixc/CatVodTVSpider/main/app/src/main/java/com/github/catvod/spider/NongMing.java > app/src/main/java/com/github/catvod/spider/NongMing.java
        #curl -L https://raw.githubusercontent.com/zhixc/CatVodTVSpider/main/app/src/main/java/com/github/catvod/spider/PiaoHua.java > app/src/main/java/com/github/catvod/spider/PiaoHua.java
        #curl -L https://raw.githubusercontent.com/zhixc/CatVodTVSpider/main/app/src/main/java/com/github/catvod/spider/SP360.java > app/src/main/java/com/github/catvod/spider/SP360.java
        #curl -L https://raw.githubusercontent.com/zhixc/CatVodTVSpider/main/app/src/main/java/com/github/catvod/spider/SixV.java > app/src/main/java/com/github/catvod/spider/SixV.java
        #curl -L https://raw.githubusercontent.com/zhixc/CatVodTVSpider/main/app/src/main/java/com/github/catvod/spider/Voflix.java > app/src/main/java/com/github/catvod/spider/Voflix.java
        #curl -L https://raw.githubusercontent.com/zhixc/CatVodTVSpider/main/app/src/main/java/com/github/catvod/spider/XingYiYing.java > app/src/main/java/com/github/catvod/spider/XingYiYing.java
        #curl -L https://raw.githubusercontent.com/zhixc/CatVodTVSpider/main/app/src/main/java/com/github/catvod/spider/Yj1211.java > app/src/main/java/com/github/catvod/spider/Yj1211.java
        #curl -L https://raw.githubusercontent.com/zhixc/CatVodTVSpider/main/app/src/main/java/com/github/catvod/spider/IQIYI.java > app/src/main/java/com/github/catvod/spider/IQIYI.java
        #curl -L https://raw.githubusercontent.com/zhixc/CatVodTVSpider/main/app/src/main/java/com/github/catvod/spider/MGTV.java > app/src/main/java/com/github/catvod/spider/MGTV.java
        #curl -L https://raw.githubusercontent.com/zhixc/CatVodTVSpider/main/app/src/main/java/com/github/catvod/spider/Cs1369.java > app/src/main/java/com/github/catvod/spider/Cs1369.java
        #curl -L https://raw.githubusercontent.com/zhixc/CatVodTVSpider/main/app/src/main/java/com/github/catvod/spider/DyGang.java > app/src/main/java/com/github/catvod/spider/DyGang.java
        #curl -L https://raw.githubusercontent.com/zhixc/CatVodTVSpider/main/app/src/main/java/com/github/catvod/spider/Xunlei8.java > app/src/main/java/com/github/catvod/spider/Xunlei8.java
        #curl -L https://raw.githubusercontent.com/zhixc/CatVodTVSpider/main/app/src/main/java/com/github/catvod/spider/PushAgent.java > app/src/main/java/com/github/catvod/spider/PushAgent.java

        #增加mymine爬虫&smb
        #curl -L https://raw.githubusercontent.com/mymine/CatVodTVSpider/main/app/src/main/java/com/github/catvod/spider/Smb4nas.java > app/src/main/java/com/github/catvod/spider/Smb4nas.java
        #curl -L https://raw.githubusercontent.com/mymine/CatVodTVSpider/main/app/src/main/java/com/github/catvod/spider/SmbProxy.java > app/src/main/java/com/github/catvod/spider/SmbProxy.java

        #Douban用回旧版本
        #curl -L https://raw.githubusercontent.com/zhixc/CatVodTVSpider/main/app/src/main/java/com/github/catvod/spider/Douban.java > app/src/main/java/com/github/catvod/spider/Douban.java
        #curl -L https://raw.githubusercontent.com/qlql765/TVJar_by_zhixc/test/app/src/main/java/com/github/catvod/spider/Douban.java > app/src/main/java/com/github/catvod/spider/Douban.java

        #增加xyzjhe爬虫
        curl -L https://raw.githubusercontent.com/xyzjhe/test_jar/refs/heads/main/app/src/main/java/com/github/catvod/spider/Freeok.java > app/src/main/java/com/github/catvod/spider/Freeok.java

        #简体化阿里云盘&alist&webdav
        sed -i 's/預設/预设/g;s/名稱/名称/g;s/時間/时间/g' app/src/main/java/com/github/catvod/spider/AList.java
        sed -i 's/預設/预设/g;s/名稱/名称/g;s/時間/时间/g' app/src/main/java/com/github/catvod/spider/WebDAV.java
        sed -i 's/轉存原畫/转存原画/g;s/分享原畫/分享原画/g;s/代理普畫/代理普画/g' app/src/main/java/com/github/catvod/spider/Ali.java
        sed -i 's/轉存原畫/转存原画/g;s/分享原畫/分享原画/g;s/代理普畫/代理普画/g;s/阿里雲盤/阿里云盘/g;s/請輸入Token/请輸入Token/g;s/請使用阿里雲盤 App 掃描二維碼/请使用阿里云盘 App 扫描二维码/g;s/來晚啦，該分享已失效/来晚了，木有了，换一个/g' app/src/main/java/com/github/catvod/api/AliYun.java

        #删除垃圾爬虫
        rm -rf app/src/main/java/com/github/catvod/spider/Ali.java
        rm -rf app/src/main/java/com/github/catvod/spider/Dm84.java
        rm -rf app/src/main/java/com/github/catvod/spider/Doll.java
        rm -rf app/src/main/java/com/github/catvod/spider/Eighteen.java
        rm -rf app/src/main/java/com/github/catvod/spider/Hanime.java
        rm -rf app/src/main/java/com/github/catvod/spider/JSDemo.java
        rm -rf app/src/main/java/com/github/catvod/spider/Jable.java
        rm -rf app/src/main/java/com/github/catvod/spider/Jianpian.java
        rm -rf app/src/main/java/com/github/catvod/spider/Kanqiu.java
        rm -rf app/src/main/java/com/github/catvod/spider/Miss.java
        rm -rf app/src/main/java/com/github/catvod/spider/Notice.java
        rm -rf app/src/main/java/com/github/catvod/spider/PanSearch.java
        rm -rf app/src/main/java/com/github/catvod/spider/PanSou.java
        rm -rf app/src/main/java/com/github/catvod/spider/Star.java
        rm -rf app/src/main/java/com/github/catvod/spider/UpYun.java
        rm -rf app/src/main/java/com/github/catvod/spider/Wogg.java
        rm -rf app/src/main/java/com/github/catvod/spider/XiaoZhiTiao.java
        rm -rf app/src/main/java/com/github/catvod/spider/YiSo.java
        rm -rf app/src/main/java/com/github/catvod/spider/Ysj.java
        rm -rf app/src/main/java/com/github/catvod/spider/Zhaozy.java
        rm -rf app/src/main/java/com/github/catvod/spider/JavDb.java
        rm -rf app/src/main/java/com/github/catvod/spider/Supjav.java

        #  #删除阿里云盘
        #  rm -rf app/src/main/java/com/github/catvod/api
        #  rm -rf app/src/main/java/com/github/catvod/bean/ali
        #  rm -rf app/src/main/java/com/github/catvod/bean/upyun

        #  sed -i "22,31d" app/src/main/java/com/github/catvod/spider/Push.java
        #  sed -i "/ali.player/c return null;" app/src/main/java/com/github/catvod/spider/Push.java
        #  sed -i "/ali.detail/d" app/src/main/java/com/github/catvod/spider/Push.java
        #  sed -i "/\"ali\"/d;/return Ali/d" app/src/main/java/com/github/catvod/spider/Proxy.java
         
        ##删除Doll残留
        #  sed -i "/Doll/d" app/src/main/java/com/github/catvod/debug/MainActivity.java

    - name: Build the Jar
      working-directory: ./project
      run: |


        #  赋予 gradlew 文件可执行权限。
        chmod +x gradlew
        #  输出 Push.java 文件的内容。
        cat app/src/main/java/com/github/catvod/spider/Push.java
        #  使用 Gradle 构建项目，启用构建缓存、并行构建、守护进程和所有警告模式。
        ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all
         
    - name: Customize Spider Jar
      working-directory: ./project
      run: |

      
        #  删除 custom_spider.jar 文件。
        rm -rf jar/custom_spider.jar
        #  删除 META-INF 目录。
        rm -rf jar/spider.jar/original/META-INF
        #  下载 apktool_2.7.0.jar 文件。
        curl -L https://github.com/iBotPeaches/Apktool/releases/download/v2.7.0/apktool_2.7.0.jar > jar/3rd/apktool_2.7.0.jar
        #  使用 baksmali 反编译 classes.dex 文件。
        java -jar jar/3rd/baksmali-2.5.2.jar d app/build/intermediates/dex/release/minifyReleaseWithR8/classes.dex -o jar/Smali_classes
        #  创建目标目录。
        mkdir -p jar/spider.jar/smali/com/github/catvod/
        #  移动反编译后的文件。
        mv jar/Smali_classes/com/github/catvod/spider jar/spider.jar/smali/com/github/catvod/
        #  使用 apktool 重新编译 Jar 文件。
        java -jar jar/3rd/apktool_2.7.0.jar b jar/spider.jar -c
        #  移动生成的 Jar 文件。
        mv jar/spider.jar/dist/dex.jar ../jar/custom_spider.jar
        #  生成 Jar 文件的 MD5 校验码并保存到文件中。
        #md5=($(md5sum ../jar/custom_spider.jar))
        echo $(md5sum ../jar/custom_spider.jar | awk '{print $1}') > ../jar/custom_spider.jar.md5

    - name: Upload APK
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Spider
        path: ./jar/custom_spider.jar

    - name: Update spider jar
      uses: EndBug/add-and-commit@v9.1.3
      with:
        default_author: github_actions
        message: 'update spider jar'
        add: "['./jar/custom_spider.jar', './jar/custom_spider.jar.md5']"